const BASE = 'https://latiendadelalgeciras.com/wp-content/uploads/';

const productos = [
    // ── EQUIPACIONES 25/26 ──────────────────────────────────────────────
    {
        nombre: 'Camiseta 1ª Equipación 25/26',
        descripcion: 'Camiseta oficial de primera equipación del Algeciras C.F., fabricada por Capelli. Producto oficial del club.',
        precio: 39.00,
        precioAnterior: null,
        imagen: BASE + 'Camiseta-algeciras-cf.jpg',
        imagenes: [BASE + 'Camiseta-algeciras-cf.jpg'],
        categoria: 'equipacion',
        tallas: ['XXS Niño', 'XS Niño', 'S Niño', 'M Niño', 'L Niño', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
        temporada: '25/26',
        activo: true,
        destacado: true,
        orden: 1,
    },
    {
        nombre: 'Camiseta 2ª Equipación 25/26',
        descripcion: 'Camiseta oficial de segunda equipación del Algeciras C.F., fabricada por Capelli. Diseño gris espacial y negro con detalles dorados.',
        precio: 39.00,
        precioAnterior: null,
        imagen: BASE + 'Segunda-camiseta-algeciras-cf.jpg',
        imagenes: [BASE + 'Segunda-camiseta-algeciras-cf.jpg'],
        categoria: 'equipacion',
        tallas: ['XXS Niño', 'XS Niño', 'S Niño', 'M Niño', 'L Niño', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
        temporada: '25/26',
        activo: true,
        destacado: true,
        orden: 2,
    },
    {
        nombre: 'Polo Capelli 25/26',
        descripcion: 'Polo oficial del Algeciras C.F. temporada 25/26, fabricado por Capelli.',
        precio: 29.95,
        precioAnterior: 39.00,
        imagen: BASE + 'Polo-algeciras-cf.jpg',
        imagenes: [BASE + 'Polo-algeciras-cf.jpg'],
        categoria: 'equipacion',
        tallas: ['S', 'M', 'L', 'XL', 'XXL'],
        temporada: '25/26',
        activo: true,
        destacado: false,
        orden: 3,
    },
    {
        nombre: 'Chaqueta Capelli 25/26',
        descripcion: 'Chaqueta oficial del Algeciras C.F. temporada 25/26, fabricada por Capelli.',
        precio: 95.00,
        precioAnterior: null,
        imagen: BASE + 'Chaqueton-algeciras-cf.jpg',
        imagenes: [BASE + 'Chaqueton-algeciras-cf.jpg'],
        categoria: 'equipacion',
        tallas: ['S Niño', 'M Niño', 'L Niño', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: '25/26',
        activo: true,
        destacado: false,
        orden: 4,
    },
    {
        nombre: 'Pantalón 1ª Equipación 25/26',
        descripcion: 'Pantalón corto azul de la primera equipación oficial del Algeciras C.F.',
        precio: 25.00,
        precioAnterior: null,
        imagen: BASE + 'PANTALON-CORTO.jpg',
        imagenes: [BASE + 'PANTALON-CORTO.jpg'],
        categoria: 'equipacion',
        tallas: ['XXS Niño', 'XS Niño', 'S Niño', 'M Niño', 'L Niño', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: '25/26',
        activo: true,
        destacado: false,
        orden: 5,
    },
    {
        nombre: 'Pantalón Paseo 25/26',
        descripcion: 'Pantalón paseo oficial del Algeciras C.F. temporada 25/26.',
        precio: 29.00,
        precioAnterior: null,
        imagen: BASE + 'Pantalon-algeciras-cf.jpg',
        imagenes: [BASE + 'Pantalon-algeciras-cf.jpg'],
        categoria: 'equipacion',
        tallas: ['S', 'M', 'L', 'XL', 'XXL'],
        temporada: '25/26',
        activo: true,
        destacado: false,
        orden: 6,
    },
    {
        nombre: 'Medias Rojas 1ª Equipación 25/26',
        descripcion: 'Medias rojas de la primera equipación del Algeciras C.F.',
        precio: 12.00,
        precioAnterior: null,
        imagen: BASE + 'medias-rojas-1a.jpg',
        imagenes: [BASE + 'medias-rojas-1a.jpg'],
        categoria: 'equipacion',
        tallas: ['XS', 'S'],
        temporada: '25/26',
        activo: true,
        destacado: false,
        orden: 7,
    },
    {
        nombre: 'Medias Negras 2ª Equipación 25/26',
        descripcion: 'Medias negras de la segunda equipación del Algeciras C.F.',
        precio: 12.00,
        precioAnterior: null,
        imagen: BASE + 'medias-negras-2a.jpg',
        imagenes: [BASE + 'medias-negras-2a.jpg'],
        categoria: 'equipacion',
        tallas: ['XS', 'S'],
        temporada: '25/26',
        activo: true,
        destacado: false,
        orden: 8,
    },
    // ── EQUIPACIONES 24/25 (liquidación) ────────────────────────────────
    {
        nombre: 'Pantalón Corto 1ª Equipación 24/25',
        descripcion: 'Pantalón azul de la primera equipación temporada 24/25.',
        precio: 29.95,
        precioAnterior: null,
        imagen: BASE + 'pantalon-1o-equi.jpg',
        imagenes: [BASE + 'pantalon-1o-equi.jpg'],
        categoria: 'equipacion',
        tallas: ['XS Niño', 'S Niño', 'M Niño', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: '24/25',
        activo: true,
        destacado: false,
        orden: 9,
    },
    // ── ENTRENAMIENTO ────────────────────────────────────────────────────
    {
        nombre: 'Camiseta Entrenamiento Capelli',
        descripcion: 'Camiseta de entrenamiento oficial del Algeciras C.F., marca Capelli.',
        precio: 29.95,
        precioAnterior: 45.00,
        imagen: BASE + 'CAMISETA-ENTRENE.jpg',
        imagenes: [BASE + 'CAMISETA-ENTRENE.jpg'],
        categoria: 'ropa',
        tallas: ['S Niño', 'M Niño', 'L Niño', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 10,
    },
    {
        nombre: 'Camiseta Entrenamiento Sin Mangas',
        descripcion: 'Camiseta sin mangas de entrenamiento oficial del Algeciras C.F.',
        precio: 29.95,
        precioAnterior: 39.95,
        imagen: BASE + 'CAMISETA-MANGA-CORTA-ENTRENE.jpg',
        imagenes: [BASE + 'CAMISETA-MANGA-CORTA-ENTRENE.jpg'],
        categoria: 'ropa',
        tallas: ['S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 11,
    },
    {
        nombre: 'Pantalón Chándal Azul',
        descripcion: 'Pantalón largo de chándal azul oficial del Algeciras C.F.',
        precio: 29.95,
        precioAnterior: 39.95,
        imagen: BASE + 'PANTALON-LARGO.jpg',
        imagenes: [BASE + 'PANTALON-LARGO.jpg'],
        categoria: 'ropa',
        tallas: ['S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 12,
    },
    // ── PASEO ────────────────────────────────────────────────────────────
    {
        nombre: 'Sudadera Roja',
        descripcion: 'Sudadera roja del Algeciras C.F. con el nombre del club al frente y escudo bordado en la manga.',
        precio: 49.95,
        precioAnterior: null,
        imagen: BASE + 'SUDADERA-ROJA-1.jpg',
        imagenes: [BASE + 'SUDADERA-ROJA-1.jpg'],
        categoria: 'ropa',
        tallas: ['10', '12', '14', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 13,
    },
    {
        nombre: 'Sudadera Negra',
        descripcion: 'Sudadera negra del Algeciras C.F. con el nombre del club en blanco y rojo y escudo bordado en la manga.',
        precio: 49.95,
        precioAnterior: null,
        imagen: BASE + 'Sudadera-Negra.jpg',
        imagenes: [BASE + 'Sudadera-Negra.jpg'],
        categoria: 'ropa',
        tallas: ['10', '12', '14', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 14,
    },
    {
        nombre: 'Pantalón Largo Chándal Negro',
        descripcion: 'Pantalón largo chándal negro oficial del Algeciras C.F.',
        precio: 29.95,
        precioAnterior: null,
        imagen: BASE + 'Pantalon-chandal-negro.jpg',
        imagenes: [BASE + 'Pantalon-chandal-negro.jpg'],
        categoria: 'ropa',
        tallas: ['XS Niño', 'M Niño', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 15,
    },
    {
        nombre: 'Bañador Bicolor',
        descripcion: 'Bañador oficial del Algeciras C.F. con franjas horizontales rojas y blancas y escudo bordado. Cintura elástica con cordón ajustable.',
        precio: 24.95,
        precioAnterior: null,
        imagen: BASE + 'Banador-Algeciras-CF.jpg',
        imagenes: [BASE + 'Banador-Algeciras-CF.jpg'],
        categoria: 'ropa',
        tallas: ['6', '8', '10', '12', '14', 'S', 'M', 'L', 'XL', 'XXL'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 16,
    },
    // ── AFICIÓN / ACCESORIOS ─────────────────────────────────────────────
    {
        nombre: 'Bufanda Premium',
        descripcion: 'Bufanda roja con el lema "SIEMPRE ALGECIRISTA" y escudo en los extremos. Reversible. 140x18cm.',
        precio: 19.00,
        precioAnterior: null,
        imagen: BASE + 'Bufanda-premium.jpg',
        imagenes: [BASE + 'Bufanda-premium.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 17,
    },
    {
        nombre: 'Bufanda Franjas Blancas',
        descripcion: 'Bufanda roja con franjas diagonales blancas en el centro. 130x20cm.',
        precio: 12.00,
        precioAnterior: null,
        imagen: BASE + 'Bufanda-franjas-blancas-algeciras.jpg',
        imagenes: [BASE + 'Bufanda-franjas-blancas-algeciras.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 18,
    },
    {
        nombre: 'Bufanda Bicolor Diagonal',
        descripcion: 'Bufanda bicolor roja y blanca del Algeciras C.F. con escudo en ambos extremos. 130x20cm.',
        precio: 12.00,
        precioAnterior: null,
        imagen: BASE + 'Bufanda-bicolor-diagonal.jpg',
        imagenes: [BASE + 'Bufanda-bicolor-diagonal.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 19,
    },
    {
        nombre: 'Gorra Blanca Adulto',
        descripcion: 'Gorra blanca del Algeciras C.F. con escudo bordado en el frontal y nombre del club en la trasera.',
        precio: 15.00,
        precioAnterior: null,
        imagen: BASE + 'Gorra-blanca.jpg',
        imagenes: [BASE + 'Gorra-blanca.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 20,
    },
    {
        nombre: 'Gorra Roja Adulto',
        descripcion: 'Gorra roja del Algeciras C.F. con escudo bordado en el frontal y nombre del club en la trasera.',
        precio: 15.00,
        precioAnterior: null,
        imagen: BASE + 'Gorra-roja.jpg',
        imagenes: [BASE + 'Gorra-roja.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 21,
    },
    {
        nombre: 'Zapatilla Hogar',
        descripcion: 'Zapatilla de hogar roja con el escudo del Algeciras C.F. en el centro.',
        precio: 24.95,
        precioAnterior: null,
        imagen: BASE + 'Zapatilla-hogar-Algeciras-cf.jpg',
        imagenes: [BASE + 'Zapatilla-hogar-Algeciras-cf.jpg'],
        categoria: 'accesorio',
        tallas: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 22,
    },
    {
        nombre: 'Toalla Roja',
        descripcion: 'Toalla roja oficial del Algeciras C.F. con escudo, nombre y año de fundación (1909) en blanco. 170x80cm.',
        precio: 14.95,
        precioAnterior: null,
        imagen: BASE + 'Toalla-Algeciras.jpg',
        imagenes: [BASE + 'Toalla-Algeciras.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 23,
    },
    {
        nombre: 'Botella Roja Monocolor',
        descripcion: 'Botella roja monocolor de 790ml con el escudo blanco del Algeciras C.F.',
        precio: 13.95,
        precioAnterior: null,
        imagen: BASE + 'Botella-monocolor.jpg',
        imagenes: [BASE + 'Botella-monocolor.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 24,
    },
    {
        nombre: 'Chanclas Franjas',
        descripcion: 'Chanclas rojas y blancas con el escudo oficial del Algeciras C.F. Perfectas para el verano.',
        precio: 11.95,
        precioAnterior: null,
        imagen: BASE + 'Chanclas-Algeciras-CF.jpg',
        imagenes: [BASE + 'Chanclas-Algeciras-CF.jpg'],
        categoria: 'accesorio',
        tallas: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 25,
    },
    {
        nombre: 'Balón Aspas Rojas',
        descripcion: 'Balón blanco con detalles rojos y el escudo del club. Talla 5 oficial Algeciras C.F.',
        precio: 19.95,
        precioAnterior: null,
        imagen: BASE + 'BALON-S5-ASPAS-ROJAS-2025.jpg',
        imagenes: [BASE + 'BALON-S5-ASPAS-ROJAS-2025.jpg'],
        categoria: 'accesorio',
        tallas: ['Talla 5'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 26,
    },
    {
        nombre: 'Bandera Algeciras CF',
        descripcion: 'Bandera roja del Algeciras CF con escudo en el centro y "ALGECIRAS CF" en blanco. Tejido resistente con costuras reforzadas. 150x100cm.',
        precio: 15.00,
        precioAnterior: null,
        imagen: BASE + 'Bandera-Algeciras-CF.jpg',
        imagenes: [BASE + 'Bandera-Algeciras-CF.jpg'],
        categoria: 'accesorio',
        tallas: ['Única'],
        temporada: null,
        activo: true,
        destacado: false,
        orden: 27,
    },
    // ── PACKS (sin stock) ────────────────────────────────────────────────
    {
        nombre: 'Pack Cantera',
        descripcion: 'Pack equipación cantera del Algeciras C.F. Consulta disponibilidad.',
        precio: 175.00,
        precioAnterior: null,
        imagen: null,
        imagenes: [],
        categoria: 'otro',
        tallas: [],
        temporada: null,
        activo: false,
        destacado: false,
        orden: 28,
    },
    {
        nombre: 'Pack Cantera + Chaquetón',
        descripcion: 'Pack equipación cantera con chaquetón del Algeciras C.F. Consulta disponibilidad.',
        precio: 210.00,
        precioAnterior: null,
        imagen: null,
        imagenes: [],
        categoria: 'otro',
        tallas: [],
        temporada: null,
        activo: false,
        destacado: false,
        orden: 29,
    },
];

async function seedProductos(Producto) {
    await Producto.bulkCreate(productos);
}

module.exports = { seedProductos };
