'use strict';

const BASE = 'https://backend-algeciras.hawkins.es/acf/noticias/';

function img(path) { return BASE + path; }

const NOTICIAS = [
  {
    titulo: 'Reconocimiento al compromiso y valentía de D. Francisco González Suárez',
    slug: 'reconocimiento-francisco-gonzalez-suarez',
    extracto: 'El Algeciras Club de Fútbol quiere rendir un merecido homenaje a D. Francisco González Suárez, inspector de la comisaría de Algeciras, quien realizará el saque de honor en el partido del próximo sábado ante el Recreativo de Huelva.',
    contenido: null,
    imagen: img('2025/01/comunicado.jpg'),
    categoria: 'comunicado',
    fecha: '2025-02-11',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Pablo Larrea, nueva incorporación del Algeciras CF',
    slug: 'pablo-larrea-nueva-incorporacion-algeciras-cf',
    extracto: 'El Algeciras CF se complace en anunciar la incorporación de Pablo Larrea Gambara (Madrid, 4 de febrero de 1994) a nuestra plantilla. El centrocampista llega para aportar experiencia, calidad y control en la medular.',
    contenido: null,
    imagen: img('2025/02/nuevo-fijachaje-Pablo-Larrea.jpg'),
    categoria: 'fichaje',
    fecha: '2025-02-04',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'ERIC MONTES, BAJA POR LESIÓN',
    slug: 'eric-montes-baja-por-lesion',
    extracto: 'El Algeciras Club de Fútbol informa que, tras las pruebas realizadas por nuestros Servicios Médicos, el jugador Eric Montes ha sido diagnosticado con una rotura del ligamento cruzado anterior (LCA).',
    contenido: null,
    imagen: img('2025/01/comunicado.jpg'),
    categoria: 'lesion',
    fecha: '2025-01-30',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Celebra tu cumpleaños en el Nuevo Mirador',
    slug: 'celebra-tu-cumpleanos-en-el-nuevo-mirador',
    extracto: 'Vive una experiencia única que incluye un Tour por el estadio y la visita de nuestra nueva mascota: SHIRA. Elige el plan que mejor se adapte a ti y haz ya tu reserva anticipada en Sport Bar "El Calvario".',
    contenido: null,
    imagen: img('2025/01/Post-Instagram-CUMPLEANOS-ACF.png'),
    categoria: 'evento',
    fecha: '2025-01-09',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'CAMPAÑA SOLIDARIA: Lanzamiento de Peluches',
    slug: 'campana-solidaria-lanzamiento-de-peluches',
    extracto: 'Este próximo sábado 21 de diciembre, durante el descanso del encuentro entre el Algeciras C.F. y Antequera C.F., realizaremos una acción solidaria en colaboración con Fundación La Caixa y Fundación A.M.B.A.E.',
    contenido: null,
    imagen: img('2024/12/ALGECIRAS-CARTELES-2024-56.png'),
    categoria: 'comunicado',
    fecha: '2024-12-16',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'CAMPAÑA DE ABONOS – 2ª VUELTA',
    slug: 'campana-de-abonos-2a-vuelta',
    extracto: 'El Algeciras Club de Fútbol abre hoy su campaña de abonos para la segunda vuelta. En este abono se incluyen todos los partidos a disputar en El Estadio Nuevo Mirador durante la segunda vuelta.',
    contenido: null,
    imagen: img('2024/12/POST-INSTAGRAM-CAMPANA.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-12-10',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Algeciras CF y Yes Energy lanzan una innovadora Comunidad Energética para los aficionados y ciudadanos del Campo de Gibraltar',
    slug: 'algeciras-cf-yes-energy-comunidad-energetica',
    extracto: 'El Algeciras Club de Fútbol, en colaboración con Yes Energy, se enorgullece de anunciar la creación de una Comunidad Energética pionera en el Campo de Gibraltar.',
    contenido: null,
    imagen: img('2024/11/Post-instagram-Yesenergy-1.png'),
    categoria: 'comunicado',
    fecha: '2024-11-06',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Parte médico: Javier Avilés',
    slug: 'parte-medico-javier-aviles',
    extracto: 'Tras las pruebas realizadas por los Servicios Médicos del Algeciras Club de Fútbol, nuestro jugador Javier Avilés ha sido diagnosticado de una rotura del LCA y una rotura vertical del asta posterior del menisco externo en su pierna derecha.',
    contenido: null,
    imagen: img('2024/10/9dad89bb-7aa5-4397-ba16-00f10f19c13b-scaled.jpeg'),
    categoria: 'lesion',
    fecha: '2024-10-25',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Parte Médico: Lucho García',
    slug: 'parte-medico-lucho-garcia',
    extracto: 'Tras las pruebas realizadas por los Servicios Médicos del Algeciras Club de Fútbol, nuestro jugador Lucho García ha sido diagnosticado de una rotura completa del tendón del recto femoral anterior derecho.',
    contenido: null,
    imagen: img('2024/10/9dad89bb-7aa5-4397-ba16-00f10f19c13b-scaled.jpeg'),
    categoria: 'lesion',
    fecha: '2024-10-10',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Jornada 7',
    slug: 'comunicado-oficial-jornada-7',
    extracto: 'Tras la solicitud del Real Betis Balompié SAD a la RFEF, esta ha confirmado que la Jornada 7 del Grupo 2 de Primera RFEF que enfrentará al Betis Deportivo y Algeciras C.F. el próximo 5 de octubre se disputará en la Ciudad Deportiva Rafael Gordillo.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1-1.png'),
    categoria: 'comunicado',
    fecha: '2024-10-02',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL',
    slug: 'comunicado-oficial-obras-estadio',
    extracto: 'Debido a las obras que se están realizando frente al estadio, les comunicamos que el próximo domingo no estará permitido el estacionamiento en toda la zona de tribuna. Rogamos disculpen las molestias.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1-1.png'),
    categoria: 'comunicado',
    fecha: '2024-09-26',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Javier Avilés, nuevo jugador del Algeciras Club de Fútbol',
    slug: 'javier-aviles-nuevo-jugador-del-algeciras-club-de-futbol',
    extracto: 'Javier Avilés Cortés (17 de Agosto de 1997, Madrid), es un extremo con mucha velocidad, una gran potencia y muy vertical. Posee un gran disparo a puerta.',
    contenido: null,
    imagen: img('2024/09/BIENVENIDO-nuevo-fichaje-20.png'),
    categoria: 'fichaje',
    fecha: '2024-09-07',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'Juan Hernández, Nuevo Jugador del Algeciras C.F.',
    slug: 'juan-hernandez-nuevo-jugador-del-algeciras-cf',
    extracto: 'El Algeciras Club de Fútbol y el Málaga C.F. han llegado a un acuerdo para la cesión del jugador Juan Hernández. Es un extremo zurdo que le gusta atacar los espacios y destaca por su velocidad.',
    contenido: null,
    imagen: img('2024/08/BIENVENIDO-nuevo-fichaje-19.png'),
    categoria: 'fichaje',
    fecha: '2024-08-29',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Ángel López',
    slug: 'comunicado-oficial-angel-lopez',
    extracto: 'Ángel López no continuará la próxima temporada en el Algeciras C.F. tras finalizar su relación contractual con el club. El Club le agradece su dedicación y profesionalidad.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1-1.png'),
    categoria: 'comunicado',
    fecha: '2024-08-29',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Neco Celorio, nuevo jugador del Algeciras C.F.',
    slug: 'neco-celorio-nuevo-jugador-del-algeciras-cf',
    extracto: 'El Algeciras C.F. y Real Racing Club han llegado a un acuerdo para la cesión de Neco Celorio. Natural de Torrelavega (Cantabria) llega en calidad de cedido para reforzar la parcela ofensiva.',
    contenido: null,
    imagen: img('2024/08/BIENVENIDO-nuevo-fichaje.png'),
    categoria: 'fichaje',
    fecha: '2024-08-21',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Comunicado oficial: Javi Cueto',
    slug: 'comunicado-oficial-javi-cueto',
    extracto: 'Javi Cueto no continuará la próxima temporada en el Algeciras C.F. tras finalizar su relación contractual con el club. El Club le agradece su dedicación y profesionalidad.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1-1.png'),
    categoria: 'comunicado',
    fecha: '2024-08-16',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Paris Adot, nuevo jugador del Algeciras C.F.',
    slug: 'paris-adot-nuevo-jugador-del-algeciras-cf',
    extracto: 'Paris Alejandro Adot Barandiaran (26 de Febrero de 1990, Pamplona), es un lateral derecho con mucho recorrido que le gusta incorporarse al ataque, con una grandísima experiencia en el fútbol profesional.',
    contenido: null,
    imagen: img('2024/08/BIENVENIDO-nuevo-fichaje-15.png'),
    categoria: 'fichaje',
    fecha: '2024-08-10',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Comunicado oficial: José Antonio Fernández Moreno "Pimienta"',
    slug: 'comunicado-oficial-jose-antonio-fernandez-pimienta',
    extracto: 'José Antonio Fernández Moreno "Pimienta" no continuará la próxima temporada en el Algeciras C.F. El Club le agradece su dedicación y profesionalidad a lo largo de estas temporadas.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1-1.png'),
    categoria: 'comunicado',
    fecha: '2024-08-10',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Selmir Miscic, nuevo jugador del Algeciras C.F.',
    slug: 'selmir-miscic-nuevo-jugador-del-algeciras-cf',
    extracto: 'Selmir Miscic (23 de Enero de 2003, Vermont, USA) es un extremo diestro habilidoso, con capacidad para asociarse bien y de desborde. Ha jugado en la USL Championship con el Philadelphia Union II y Portland Timbers II.',
    contenido: null,
    imagen: img('2024/08/BIENVENIDO-nuevo-fichaje.png'),
    categoria: 'fichaje',
    fecha: '2024-08-09',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Trofeo Diputación Virgen de La Palma 2024',
    slug: 'trofeo-diputacion-virgen-de-la-palma-2024',
    extracto: 'El próximo sábado 17 de agosto a las 19:00h disfrutaremos de nuevo en el Nuevo Mirador del Trofeo Diputación Virgen de la Palma, patrocinado por Diputación de Cádiz, con nuestro vecino A.D. Ceuta.',
    contenido: null,
    imagen: img('2024/08/Trofeo-diputacion-cartel-Instagram-4.png'),
    categoria: 'evento',
    fecha: '2024-08-09',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'La selección Española Sub 21 en el Nuevo Mirador',
    slug: 'la-seleccion-espanola-sub-21-en-el-nuevo-mirador',
    extracto: 'La Real Federación Española de Fútbol confirma el Estadio Nuevo Mirador como sede para el partido clasificatorio europeo de 2025 de la selección sub 21 contra Malta, el Martes 15 de octubre de 2024.',
    contenido: null,
    imagen: img('2024/08/CARTELES-PARTIDOS-1.png'),
    categoria: 'evento',
    fecha: '2024-08-02',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'Lautaro Spatz, Nuevo jugador del Algeciras C.F.',
    slug: 'lautaro-spatz-nuevo-jugador-del-algeciras-cf',
    extracto: 'Lautaro Marco Spatz (19 de Octubre de 2001, Buenos Aires), es un central muy contundente, con un extraordinario juego aéreo y con una buena salida de balón en conducción.',
    contenido: null,
    imagen: img('2024/07/BIENVENIDO-nuevo-fichaje-13-2.png'),
    categoria: 'fichaje',
    fecha: '2024-07-17',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Aleix Coch, nuevo jugador del Algeciras C.F.',
    slug: 'aleix-coch-nuevo-jugador-del-algeciras-cf',
    extracto: 'Aleix Coch Lucena (18 de Octubre de 1991, Tarragona) es un jugador con mucha experiencia en la tercera categoría del fútbol español, un central expeditivo con gran colocación y un gran juego aéreo.',
    contenido: null,
    imagen: img('2024/07/BIENVENIDO-nuevo-fichaje-1-1.png'),
    categoria: 'fichaje',
    fecha: '2024-07-12',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Javi Alonso, Nuevo jugador del Algeciras C.F.',
    slug: 'javi-alonso-nuevo-jugador-del-algeciras-cf',
    extracto: 'Javi Alonso Bello (01 de Agosto de 1998, Sta Cruz de Tenerife) es un mediocentro zurdo que atesora mucha calidad y se caracteriza por ser tácticamente inteligente y por su manera de entender el juego.',
    contenido: null,
    imagen: img('2024/07/Javi-Alonso.png'),
    categoria: 'fichaje',
    fecha: '2024-07-08',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Javi Gómez, Nuevo jugador del Algeciras C.F.',
    slug: 'javi-gomez-nuevo-jugador-del-algeciras-cf',
    extracto: 'Javi Gómez Castroverde (10 de Enero de 1999, Toledo) es un extremo ambidiestro que se desenvuelve a la perfección en ambas bandas, habilidoso, rápido con un excelente golpeo tanto a portería como a balón parado.',
    contenido: null,
    imagen: img('2024/07/Javi-Gomez.png'),
    categoria: 'fichaje',
    fecha: '2024-07-04',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Manín, nuevo Jugador del Algeciras C.F.',
    slug: 'manin-nuevo-jugador-del-algeciras-cf',
    extracto: 'Luis Gonzaga Delage Cruzado "Manín" (13 de Enero del 2000, Jerez de la Frontera) es un delantero centro zurdo con gran intuición dentro del área, con muy buen remate de cabeza y una excelente definición.',
    contenido: null,
    imagen: img('2024/07/BIENVENIDO-nuevo-fichaje-16.png'),
    categoria: 'fichaje',
    fecha: '2024-07-03',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Iker Venteo Plaza, nuevo jugador del Algeciras C.F.',
    slug: 'iker-venteo-plaza-nuevo-jugador-del-algeciras-cf',
    extracto: 'Iker Venteo Plaza (24 de Abril de 2003, Vilanova del Camí, Barcelona) es un portero de 1,91m de altura que se caracteriza por sus reflejos bajo palos, por su seguridad en el juego aéreo y por su carácter competitivo.',
    contenido: null,
    imagen: img('2024/07/BIENVENIDO-nuevo-fichaje-14.png'),
    categoria: 'fichaje',
    fecha: '2024-07-02',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'Arnau Gaixas, nuevo jugador del Algeciras C.F.',
    slug: 'arnau-gaixas-nuevo-jugador-del-algeciras-cf',
    extracto: 'Arnau Gaixas Pont (05 de Julio de 1998, Vilassar de Mar, Barcelona) es un defensa central zurdo ágil, con buena salida de balón, muy competitivo y con una gran capacidad táctica y de lectura de juego.',
    contenido: null,
    imagen: img('2024/07/BIENVENIDO-nuevo-fichaje.png'),
    categoria: 'fichaje',
    fecha: '2024-07-02',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Rodrigo Escudero Vega, Nuevo jugador del Algeciras C.F.',
    slug: 'rodrigo-escudero-vega-nuevo-jugador-del-algeciras-cf',
    extracto: 'Rodrigo Escudero Vega (31 de Marzo de 1994, Simancas) es un delantero centro cuyas características son el buen golpeo con las dos piernas, un buen remate de cabeza y la capacidad de asociación.',
    contenido: null,
    imagen: img('2024/07/BIENVENIDO-nuevo-fichaje-13.png'),
    categoria: 'fichaje',
    fecha: '2024-07-01',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'NUEVO ABONO BABY: Algecirista de cuna',
    slug: 'nuevo-abono-baby-algecirista-de-cuna',
    extracto: 'Damos la bienvenida al mundo a los nuevos algeciristas poniendo en marcha una iniciativa en la que recibirá regalos con su primer carné de socio. Con los años, siempre podrá decir con orgullo que es socio algecirista desde que nació.',
    contenido: null,
    imagen: img('2024/07/WhatsApp-Image-2024-07-01-at-11.12.26-scaled.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-07-01',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'FRAN JUSTO: Nuevo entrenador del Algeciras C.F.',
    slug: 'fran-justo-nuevo-entrenador-del-algeciras-cf',
    extracto: 'Fran Justo será el nuevo entrenador del Algeciras CF. Natural de Ourense (24/08/1989), se inició en los banquillos de su ciudad natal donde acabó dirigiendo al primer equipo del Ourense C.F., al que ascendió a Tercera División.',
    contenido: null,
    imagen: img('2024/06/BIENVENIDO-nuevo-fichaje-8.png'),
    categoria: 'fichaje',
    fecha: '2024-06-28',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Zequi Díaz',
    slug: 'comunicado-oficial-zequi-diaz-no-renueva',
    extracto: 'El jugador Zequi Díaz no continuará la próxima temporada en el Algeciras C.F. tras llegar a un acuerdo con el club. El Club le agradece su dedicación y profesionalidad.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1-1.png'),
    categoria: 'comunicado',
    fecha: '2024-06-25',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'INFORMACIÓN CAMPAÑA DE ABONOS: NUEVAS ALTAS',
    slug: 'informacion-campana-de-abonos-nuevas-altas',
    extracto: 'Os recordamos que a partir del domingo 16 de junio estarán disponibles las nuevas altas en nuestra web. A partir del lunes 17 de junio podrá hacer su alta nueva en nuestra tienda física.',
    contenido: null,
    imagen: img('2024/06/INSTAGRAM-CAMPANA-ABONOS.png'),
    categoria: 'comunicado',
    fecha: '2024-06-14',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'INFORMACIÓN CAMPAÑA DE ABONOS',
    slug: 'informacion-campana-de-abonos',
    extracto: 'Os recordamos que a partir de mañana lunes 10 de junio, se procederá a la liberación de los asientos que no hayan sido renovados, y comenzará el periodo de cambios de asientos para aquellos que quieran optar por otra ubicación.',
    contenido: null,
    imagen: img('2024/06/Copia-de-Comunicado202425-ALGECIRAS-CF-1.png'),
    categoria: 'comunicado',
    fecha: '2024-06-09',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Algeciras C.F. B – C.D. Guadiaro',
    slug: 'comunicado-oficial-algeciras-cf-b-cd-guadiaro',
    extracto: 'Por motivos de seguridad, el partido de este domingo 2 de junio a las 11:30 entre el Algeciras C.F. B y el C.D. Guadiaro se celebrará en el Estadio Nuevo Mirador.',
    contenido: null,
    imagen: img('2024/05/e0cd1a52-028d-4e5c-9be5-b1f9cefe6e81.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-05-29',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'CAMPAÑA DE ABONOS 24-25',
    slug: 'campana-de-abonos-24-25',
    extracto: 'Para cualquier consulta relacionada con abonos, puede ponerse en contacto con nosotros a través de: Email: info@algecirasclubdefutbol.com. Teléfono: 956 66 63 46.',
    contenido: null,
    imagen: img('2024/05/para-instagram-algeciras-02.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-05-28',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Situación actual de la plantilla',
    slug: 'comunicado-oficial-situacion-actual-de-la-plantilla',
    extracto: 'La situación actual de la plantilla del Algeciras Club de Fútbol: Con contrato en vigor: Rafa Roldán, Eric Montes, Zequi Díaz, Javi Cueto, Diego Esteban, Tomás Sánchez, Lucho García, Juan Rodríguez, Dani Merchán, Iker Navarro, José Antonio Fernández, Francisco Manuel Domínguez.',
    contenido: null,
    imagen: img('2024/02/e0cd1a52-028d-4e5c-9be5-b1f9cefe6e81.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-05-27',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Lolo Escobar',
    slug: 'comunicado-oficial-lolo-escobar',
    extracto: 'Lolo Escobar y su cuerpo técnico no continuarán la próxima temporada en el Algeciras C.F. al finalizar su contrato con la entidad el 30 de junio de 2024. El Club les agradece su dedicación y profesionalidad.',
    contenido: null,
    imagen: img('2024/02/e0cd1a52-028d-4e5c-9be5-b1f9cefe6e81.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-05-27',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Zequi Díaz renueva',
    slug: 'comunicado-oficial-zequi-diaz-renueva',
    extracto: 'El extremo continuará durante la próxima temporada 24/25 vistiendo nuestros colores tras alcanzar los objetivos para su renovación. ¡Felicidades Zequi, crecemos contigo!',
    contenido: null,
    imagen: img('2024/04/0aaca4e8-7370-4a0a-8ce8-afadbc02091b-scaled.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-04-04',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Comunicado oficial: Lucho García renueva',
    slug: 'comunicado-oficial-lucho-garcia-renueva',
    extracto: 'Nuestro guardameta continuará durante la próxima temporada 24/25 defendiendo nuestra portería tras conseguir los objetivos fijados para su renovación. ¡Felicidades Lucho, crecemos contigo!',
    contenido: null,
    imagen: img('2024/03/6236beee-2b93-485d-bf9a-513d94b3bef0-scaled.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-03-24',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Linares',
    slug: 'galeria-algeciras-linares',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y Linares.',
    contenido: null,
    imagen: img('2024/03/image00122-scaled.jpeg'),
    categoria: 'galeria',
    fecha: '2024-03-18',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Partido Algeciras C.F. – Málaga C.F.',
    slug: 'comunicado-oficial-partido-algeciras-cf-malaga-cf',
    extracto: 'Desde el día de hoy, jueves 14 de marzo, hasta el sábado 16 de marzo a las 13:00, se realizará de forma presencial en nuestra tienda la venta exclusiva de entradas para abonados.',
    contenido: null,
    imagen: img('2024/03/Comunicado-Oficial-POST-ALGECIRAS-CF-9.png'),
    categoria: 'partido',
    fecha: '2024-03-14',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'Galería | Algeciras – Recreativo Granada',
    slug: 'galeria-algeciras-recreativo-granada',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y Recreativo Granada.',
    contenido: null,
    imagen: img('2024/03/image00011-scaled.jpeg'),
    categoria: 'galeria',
    fecha: '2024-03-05',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Reparto de puntos ante el Recreativo Granada (1-1)',
    slug: 'reparto-de-puntos-ante-el-recreativo-granada-1-1',
    extracto: 'El Algeciras CF encaraba una nueva jornada en el estadio Nuevo Mirador para recibir al Recreativo Granada en la 26ª jornada del Grupo II de la Primera Federación.',
    contenido: null,
    imagen: img('2024/03/WhatsApp-Image-2024-03-02-at-18.12.14-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2024-03-02',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Tablas en el derbi provincial (0-0)',
    slug: 'tablas-en-el-derbi-provincial-0-0',
    extracto: 'El Algeciras CF visitó el estadio El Palmar para albergar el último derbi provincial del curso, frente a un Atlético Sanluqueño escalando desde la zona baja.',
    contenido: null,
    imagen: img('2024/02/IMG_7354-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2024-02-25',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Comunicado oficial: Juan Rodríguez RENOVADO',
    slug: 'comunicado-oficial-juan-rodriguez-renovado',
    extracto: 'Juan Rodríguez continuará de nuestra mano durante la próxima temporada 24/25, tras conseguir los objetivos fijados para su renovación. ¡Felicidades Juan, crecemos contigo!',
    contenido: null,
    imagen: img('2024/02/44b46202-b0f8-4523-b45a-08e272808114-scaled.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-02-20',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Castilla',
    slug: 'galeria-algeciras-castilla',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y Real Madrid Castilla.',
    contenido: null,
    imagen: img('2024/02/e0cd1a52-028d-4e5c-9be5-b1f9cefe6e81.jpeg'),
    categoria: 'galeria',
    fecha: '2024-02-20',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Comunicado oficial: Rafa Roldán renueva',
    slug: 'comunicado-oficial-rafa-roldan-renueva',
    extracto: 'Nuestro jugador continuará durante la próxima temporada 24/25 vistiendo los colores rojiblancos tras conseguir los objetivos fijados para su renovación. ¡Felicidades Rafa, crecemos contigo!',
    contenido: null,
    imagen: img('2024/02/926a4fa8-7798-4424-b44e-fbcf64d389fa-scaled.jpeg'),
    categoria: 'comunicado',
    fecha: '2024-02-19',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Brillante victoria del Algeciras en el Nuevo Mirador (3-0)',
    slug: 'brillante-victoria-del-algeciras-en-el-nuevo-mirador-3-0',
    extracto: 'El Algeciras CF volvía al estadio Nuevo Mirador para recibir al Real Madrid Castilla en la 24ª jornada del Grupo II de Primera Federación. El conjunto rojiblanco impuso su ley con una brillante victoria.',
    contenido: null,
    imagen: img('2024/02/13B00813-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2024-02-17',
    activo: true,
    destacado: true,
  },
  {
    titulo: 'El Algeciras cae por la mínima en Alicante (1-0)',
    slug: 'el-algeciras-cae-por-la-minima-en-alicante-1-0',
    extracto: 'El Algeciras CF visitó el estadio Antonio Solana para enfrentarse al CF Intercity en un encuentro clave para las ilusionantes aspiraciones de ambos equipos.',
    contenido: null,
    imagen: img('2024/02/39c8c1b3-b89d-4a66-b820-c8d52195edbd-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2024-02-10',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Alcoyano',
    slug: 'galeria-algeciras-alcoyano',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y CD Alcoyano.',
    contenido: null,
    imagen: img('2024/02/image00045-scaled.jpeg'),
    categoria: 'galeria',
    fecha: '2024-02-06',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras consigue un punto aguantando con diez hombres (1-1)',
    slug: 'el-algeciras-consigue-un-punto-aguantando-con-diez-hombres-1-1',
    extracto: 'El Algeciras CF aguardaba en el estadio Nuevo Mirador para recibir al CD Alcoyano en la 22ª jornada del Grupo II de Primera Federación. El conjunto albirrojo recuperó al capitán Iván Turrillo.',
    contenido: null,
    imagen: img('2024/02/WhatsApp-Image-2024-02-03-at-18.42.56-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2024-02-03',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Sergio Santos, Nuevo jugador del Algeciras C.F.',
    slug: 'sergio-santos-nuevo-jugador-del-algeciras-cf',
    extracto: 'Sergio Santos se incorpora al Algeciras C.F. hasta final de temporada. El jugador llega en calidad de cedido desde el Real Murcia C.F. Sergio, criado en la cantera del Real Madrid C.F., actúa como lateral derecho.',
    contenido: null,
    imagen: img('2024/02/WhatsApp-Image-2024-02-01-at-22.45.19-scaled.jpeg'),
    categoria: 'fichaje',
    fecha: '2024-02-01',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras sigue sumando en el derbi gaditano (0-0)',
    slug: 'el-algeciras-sigue-sumando-en-el-derbi-gaditano-0-0',
    extracto: 'El Algeciras CF visitó el estadio Iberoamericano 2010 para encarar el primer viaje del segundo tramo de la competición hacia uno de los derbis provinciales de la temporada.',
    contenido: null,
    imagen: img('2024/01/WhatsApp-Image-2024-01-28-at-21.39.25.jpeg'),
    categoria: 'partido',
    fecha: '2024-01-28',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Javi López-Pinto, Nuevo jugador del Algeciras C.F.',
    slug: 'javi-lopez-pinto-nuevo-jugador-del-algeciras-cf',
    extracto: 'Javi López-Pinto se incorpora al Algeciras C.F. hasta final de temporada. El jugador llega en calidad de cedido desde el Burgos C.F., equipo con el que ha debutado en 2ª división.',
    contenido: null,
    imagen: img('2024/01/Javi-Lopez.png'),
    categoria: 'fichaje',
    fecha: '2024-01-26',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Cesión de Marino Illescas',
    slug: 'comunicado-oficial-cesion-marino-illescas',
    extracto: 'El Algeciras C.F. y el C.D. Arenteiro llegan a un acuerdo para la cesión del jugador Marino Illescas hasta final de temporada.',
    contenido: null,
    imagen: img('2023/10/Comunicado-Oficial-POST-ALGECIRAS-CF-1.png'),
    categoria: 'comunicado',
    fecha: '2024-01-22',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Melilla',
    slug: 'galeria-algeciras-melilla',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y UD Melilla.',
    contenido: null,
    imagen: img('2024/01/DSC03575-scaled.jpg'),
    categoria: 'galeria',
    fecha: '2024-01-22',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras triunfa bajo un cielo gris (1-0)',
    slug: 'el-algeciras-triunfa-bajo-un-cielo-gris-1-0',
    extracto: 'El Algeciras CF volvió al estadio Nuevo Mirador para recibir el primer encuentro de la segunda vuelta del campeonato: el duelo de la 20ª jornada frente a la UD Melilla.',
    contenido: null,
    imagen: img('2024/01/13B00633-scaled.jpg'),
    categoria: 'partido',
    fecha: '2024-01-21',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras lucha, pero cae ante el líder (2-1)',
    slug: 'el-algeciras-lucha-pero-cae-ante-el-lider-2-1',
    extracto: 'El Algeciras CF visitó el estadio de Castalia para medirse al destacado CD Castellón en el último encuentro de la primera vuelta de la temporada.',
    contenido: null,
    imagen: img('2024/01/WhatsApp-Image-2024-01-13-at-20.02.44-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2024-01-13',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Comunicado Oficial: Jack Imperato',
    slug: 'comunicado-oficial-jack-imperato',
    extracto: 'El jugador del Algeciras C.F., Jack Imperato, ha decidido retirarse de los terrenos de juego tras las diferentes pruebas médicas realizadas. El jugador sufre una lesión crónica que le impedirá seguir con la práctica del fútbol.',
    contenido: null,
    imagen: img('2024/01/Comunicado-Oficial-POST-ALGECIRAS-CF-1.png'),
    categoria: 'comunicado',
    fecha: '2024-01-03',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'COMUNICADO OFICIAL: Rodrigo Sanz',
    slug: 'comunicado-oficial-rodrigo-sanz',
    extracto: 'Rodrigo Sanz no continuará durante lo que resta de temporada en el Algeciras C.F. tras llegar a un acuerdo entre el jugador y la entidad.',
    contenido: null,
    imagen: img('2024/01/Comunicado-Oficial-POST-ALGECIRAS-CF-1.png'),
    categoria: 'comunicado',
    fecha: '2024-01-03',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Recreativo de Huelva',
    slug: 'galeria-algeciras-recreativo-de-huelva',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y Recreativo de Huelva.',
    contenido: null,
    imagen: img('2024/01/13B05086-scaled.jpg'),
    categoria: 'galeria',
    fecha: '2024-01-02',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras cae en el descuento en el primer partido del año (2-3)',
    slug: 'el-algeciras-cae-en-el-descuento-en-el-primer-partido-del-ano-2-3',
    extracto: 'El estadio Nuevo Mirador recibía con ambiente de gala el 2024 para albergar el primer partido del año, frente al Recreativo de Huelva en la 18ª jornada del Grupo II de Primera Federación.',
    contenido: null,
    imagen: img('2024/01/13B05151-scaled.jpg'),
    categoria: 'partido',
    fecha: '2024-01-02',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Málaga – Algeciras',
    slug: 'galeria-malaga-algeciras',
    extracto: 'Galería fotográfica del partido entre Málaga C.F. y Algeciras C.F. en La Rosaleda.',
    contenido: null,
    imagen: img('2023/12/06-scaled.jpg'),
    categoria: 'galeria',
    fecha: '2023-12-18',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras muere en la orilla de La Rosaleda (2-1)',
    slug: 'el-algeciras-muere-en-la-orilla-de-la-rosaleda-2-1',
    extracto: 'El Algeciras CF visitó el estadio La Rosaleda para medirse frente al Málaga CF en el último encuentro liguero del año 2023 en la 17ª jornada. El conjunto albirrojo fue acompañado por más de un millar de aficionados.',
    contenido: null,
    imagen: img('2023/12/WhatsApp-Image-2023-12-17-at-20.42.54-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2023-12-17',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Ibiza',
    slug: 'galeria-algeciras-ibiza',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y UD Ibiza.',
    contenido: null,
    imagen: img('2023/12/13B04377-scaled.jpg'),
    categoria: 'galeria',
    fecha: '2023-12-12',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'El Algeciras compite como un gigante (0-0)',
    slug: 'el-algeciras-compite-como-un-gigante-0-0',
    extracto: 'El Algeciras CF regresó al estadio Nuevo Mirador para disputar el último encuentro del año 2023 frente a la UD Ibiza, un equipo inmerso en la lucha por el liderato.',
    contenido: null,
    imagen: img('2023/12/13B04662-scaled.jpg'),
    categoria: 'partido',
    fecha: '2023-12-10',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'La muralla algecirista asalta El Maulí (0-1)',
    slug: 'la-muralla-algecirista-asalta-el-mauli-0-1',
    extracto: 'El Algeciras CF visitó el estadio El Maulí para medirse frente al Antequera CF en la 15ª jornada, ante uno de los equipos revelación de la temporada.',
    contenido: null,
    imagen: img('2023/12/WhatsApp-Image-2023-12-03-at-18.49.21-scaled.jpeg'),
    categoria: 'partido',
    fecha: '2023-12-03',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Galería | Algeciras – Atleti B',
    slug: 'galeria-algeciras-atleti-b',
    extracto: 'Galería fotográfica del partido entre Algeciras C.F. y Atlético de Madrid B.',
    contenido: null,
    imagen: img('2023/11/13B00033-scaled.jpg'),
    categoria: 'galeria',
    fecha: '2023-11-27',
    activo: true,
    destacado: false,
  },
  {
    titulo: 'Tablas en el Nuevo Mirador (2-2)',
    slug: 'tablas-en-el-nuevo-mirador-2-2',
    extracto: 'El Algeciras CF regresó al Nuevo Mirador para encarar la 14ª jornada en el Grupo II de Primera Federación. El conjunto rojiblanco, tras una victoria de trabajo y orgullo frente al Real Madrid Castilla, se enfrentó al Atlético de Madrid B.',
    contenido: null,
    imagen: img('2023/11/WhatsApp-Image-2023-11-26-at-20.21.04.jpeg'),
    categoria: 'partido',
    fecha: '2023-11-26',
    activo: true,
    destacado: false,
  },
];

async function seedNoticias(Noticia) {
  let count = 0;
  for (const n of NOTICIAS) {
    try {
      await Noticia.create(n);
      count++;
    } catch (err) {
      console.error(`Error noticia "${n.slug}":`, err.message);
    }
  }
  console.log(`Sembradas ${count}/${NOTICIAS.length} noticias`);
}

module.exports = { seedNoticias };
